name: local_notification_service
description: Local notification service module
version: 3.1.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  rxdart: ^0.28.0
  timezone: ^0.10.1

  common_result:
    git:
      url: git@github.com:nove8/fl-common-result.git
      ref: 4.0.0

dev_dependencies:
  common_package:
    git:
      url: git@github.com:nove8/fl-common-package.git
      ref: 4.1.0
