name: device_info_service
description: Device info service module
version: 3.0.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  flutter:
    sdk: flutter

  async: ^2.13.0
  device_info_plus: ^12.2.0

  common_result:
    git:
      url: git@github.com:nove8/fl-common-result.git
      ref: 4.0.0

dev_dependencies:
  common_package:
    git:
      url: git@github.com:nove8/fl-common-package.git
      ref: 4.0.0
