name: preferences_service
description: Preferences service module
version: 2.1.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  shared_preferences: ^2.5.3

  common_result:
    git:
      url: git@github.com:nove8/fl-common-result.git
      ref: 4.0.0

dev_dependencies:
  common_package:
    git:
      url: git@github.com:nove8/fl-common-package.git
      ref: 4.0.0
