name: permission_service
description: Permission service module
version: 2.2.1
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: ^3.38.3

dependencies:
  flutter:
    sdk: flutter

  async: ^2.13.0
  permission_handler: ^12.0.1

  common_result:
    git:
      url: git@github.com:nove8/fl-common-result.git
      ref: 4.0.0

dev_dependencies:
  common_package:
    git:
      url: git@github.com:nove8/fl-common-package.git
      ref: 4.1.0
